publint/publint

pnpm-lock.yaml
site/package.json

The following error was happening when running `pnpm i`. I guess this can be `workspace:*` instead of `workspace:0.1.1`.
> ERR_PNPM_NO_MATCHING_VERSION_INSIDE_WORKSPACE  In site: No matching version found for publint@0.1.1 inside the workspace

Fix publint dep version in site/package.json

---

site/src/pages/Package.svelte

Adds more repo URL formats.
1. URL starting from `git://`: https://publint.bjornlu.com/object-define-property@0.1.0
1. `repository` field having `string` directly instead of `object`: https://publint.bjornlu.com/for-each@0.3.3

Support more repo URL formats

---

pkg/index.d.ts
pkg/src/index.js
pkg/src/message.js
pkg/tests/fixtures/exports-module/main.js
pkg/tests/fixtures/exports-module/main.mjs
pkg/tests/fixtures/exports-module/package.json
pkg/tests/playground.js
site/rules.md
site/src/utils/message.js

This provides a fix for common bugs like this:
{
"exports": {
".": {
"import": "./dist/index.mjs",
"require": "./dist/index.js",
"module": "./dist/index.mjs",  // ⚠️
}
}
}
Due to the way conditions are checked top-to-bottom, the `module` definition has no chance to take precedence over `import` and `require`—which is typically the whole point of including `module`. Bundler implementations may chose to not respect definition order (so some bundlers may work _despite_ the incorrect order of the `module` field), but it's not the way the conditions are supposed to be checked. By enforcing `module` to appear before `import` and/or `require`, this problem is circumvented and should work in _all_ bundlers.
The fix for the above is to move the `"module"` definition up:
{
"exports": {
".": { …

Check that `module` preceeds `import` and `require` in exports definitions

---

pkg/index.d.ts
pkg/src/index.js
pkg/src/message.js
pkg/tests/playground.js
site/rules.md
site/src/utils/message.js

The lint rule I contributed recently in https://github.com/bluwy/publint/pull/49 may have been a tad bit too strict. Some package authors prefer to use the `module` condition to override the `require` (or `default`) condition only, but not using it for `import` statements. That should be fine. The purpose of the bundler-specific `module` condition is to allow you to override/intercept `require()`s mostly, and instruct the bundler to include the ESM version instead.
As a package author, you can still also decide to place the `module` condition before the `import` and as such use it to _also_ intercept `import` statements. Both approaches are fine, as a `module` and `import` definition will typically resolve to the same module in practice. So it's mostly an author preference, and not …

Don't enforce `module` to precede `import` per se

---

site/rules.md

Changed `import` to `require` for the CJS exports.

Fix EXPORT_TYPES_INVALID_FORMAT example

---

pkg/src/index.js
pkg/tests/fixtures/test-2/package.json
pkg/tests/playground.js

`typings` field can also be used to point to the type definition file. (it's just an alias of `types` field)
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package
I simply added to the file existence check.
I can think of setting different values to `types` and `typings` but I believe no one would do that, so I didn't add that rule.

Lint typings field file existence

---

site/src/pages/Package.svelte

At present, if the wrong package name causes a 404 request, the page will always display loading.

Fix invalid package name should show not found

---

pkg/index.d.ts
pkg/src/index.js
pkg/src/message.js
pkg/tests/playground.js
site/rules.md
site/src/utils/message.js

- Splits `USE_EXPORTS_BROWSER` into `USE_EXPORTS_BROWSER` and `USE_EXPORTS_OR_IMPORTS_BROWSER` depending on the value of `browser` field
- Add a document that `imports` field can be used to do the same thing with `browser` field
I think my wordings are not good so feel free to completely rewrite the message😅

Improve browser field suggestion

---

site/rules.html
site/scripts/vitePluginMarkdown.js
site/src/global.css
site/src/rules.js

Add sidebar menu to rules page

---

site/src/components/PkgNode.svelte

The type of `key` does not match the parameter type of `parseInt`.

Resolve site ts error

---

pkg/index.d.ts
pkg/src/index.js
pkg/src/message.js
pkg/tests/fixtures/deprecated-fields/package.json
pkg/tests/playground.js
site/rules.md
site/src/utils/message.js

`jsnext` and `jsnext:main` fields are superseded by `module` field (https://github.com/jsforum/jsforum/issues/5, https://github.com/rollup/rollup/wiki/pkg.module#:~:text=(Note%3A%20Tools%20such%20as%20rollup%2Dplugin%2Dnode%2Dresolve%20and%20Webpack%202%20treat%20jsnext%3Amain%20and%20module%20interchangeably.%20They%27re%20the%20same%20thing%2C%20except%20that%20module%20is%20more%20likely%20to%20become%20standardised.)).
This PR adds a warning for those fields.

Add a warning for jsnext field

---

pkg/src/message.js
pkg/utils.d.ts

Add `formatMessage` `color` option

---

.changeset/warm-dingos-sparkle.md
packages/publint/src/cli.js
packages/publint/src/index-node.js
packages/publint/src/index.d.ts

Currently, the new `--pack` CLI option gets ignored by the publint function, and is also handled incorrectly when the value is not `auto`.
This PR makes 2 changes:
- Pass `--pack` option from CLI into `lintDir`, then into `publint`
- Only use `package-manager-detector` when `pack` is `auto` (otherwise use the manual option, e.g. `--pack npm`)
To make types work, I've needed to add `deno` as a valid option to pass to the CLI, however  this still gets turned into `npm` internally

Correctly process the pack option

---

.changeset/four-pears-push.md
packages/publint/src/index.d.ts
packages/publint/src/node/message.js
packages/publint/src/shared/core.js
packages/publint/tests/playground.test.js
site/src/app/utils/message.js
site/src/pages/rules.md

Resolving this TODO about renaming the rule. Since this is a breaking change let me know how you'd like to proceed.

Rename EXPORT_TYPES_INVALID_FORMAT to EXPORTS_TYPES_INVALID_FORMAT

---

.changeset/loose-ducks-cross.md
packages/publint/src/shared/core.js
packages/publint/tests/fixtures/types-exports-versioned.js
packages/publint/tests/playground.test.js

Allows for versioned `types` conditions to precede the default `types` condition in exports
Closes https://github.com/publint/publint/issues/137

Allow versioned types conditions in exports

---

package.json

pnpm 10 no longer executes scripts by default and needs to be specified manually.

Add `esbuild` and `sharp` to pnpm.onlyBuiltDependencies

---

packages/publint/src/node/message.js
site/src/app/utils/message.js

Updates some of the messages to change "NodeJS" to the official name "Node.js"

Change NodeJS to Node.js in messages

---

.changeset/clean-wolves-clean.md
packages/publint/src/index.d.ts
packages/publint/src/node/message.js
packages/publint/src/shared/core.js
packages/publint/src/shared/utils.js
packages/publint/tests/fixtures/bin-file-missing-node-shebang.js
packages/publint/tests/fixtures/bin-file-missing-shebang.js
packages/publint/tests/fixtures/bin-file-not-lintable.js
packages/publint/tests/fixtures/missing-files.js
packages/publint/tests/playground.test.js
site/src/app/utils/message.js
site/src/pages/rules.md

Adds support for checking files in the bin field.  This PR the following checks
* checks the files exist
* checks the files are the correct format
* checks the files start with a node shebang as mentioned in the [package.json#bin](https://docs.npmjs.com/cli/v11/configuring-npm/package-json#bin)
Closes https://github.com/publint/publint/issues/145

Add support for checking files in bin field

---

.changeset/brown-paths-enjoy.md
packages/publint/src/index.d.ts
packages/publint/src/node/message.js
packages/publint/src/shared/core.js
site/src/app/utils/message.js
site/src/pages/rules.md

Adds two additional rules for the `"imports"` fields:
1. `IMPORTS_MODULE_SHOULD_PRECEDE_REQUIRE` to check that the `"module"` conditions comes before the `"require"` condition.
2. `IMPORTS_MODULE_SHOULD_BE_ESM` to check that the `"module"` condition resolves to a file that is ESM.

Support additional rules for imports field

---

.changeset/eighty-bears-ask.md
packages/publint/src/shared/core.js
packages/publint/src/shared/message.js
site/src/pages/rules.md

Updated the message of EXPORTS_GLOB_NO_DEPRECATED_SUBPATH_MAPPING as the support for it was removed in Node 17.
Also updated the severity to error from warning as all versions supporting that feature has reached EOL.

Update EXPORTS_GLOB_NO_DEPRECATED_SUBPATH_MAPPING message and severity

---

.changeset/blue-areas-obey.md
packages/publint/src/shared/utils.js

The shebang can contain whitespace between the `#!` and `/`, which should not cause checks to fail.

Fix shebang check

---

site/src/app/pages/Package.svelte

When switching between different versions for comparison, click the npm link to view the specific code with the version number to facilitate code comparison.

Add version number to npm url

---

analysis/index.js
packages/pack/src/node/pack-as-list.js
packages/pack/src/node/unpack.js
packages/publint/src/cli.js
site/src/app/pages/Package.svelte
site/src/pages/docs/javascript-api.md

Adds support for slicing ArrayBuffers when working with tarballs in the pack/unpack utilities. 
This allows for more flexible manipulation of tarball contents before parsing.
All existing tests pass; new test coverage may be added for sliced buffers if needed.
fix #193

Slice ArrayBuffer from Buffer

---

packages/publint/src/shared/utils.js
packages/publint/tests/utils.test.js

Follow up to #201
Improved the regex to match `exports["default"]` and `exports['default']`.
I found this pattern in `typesense-instantsearch-adapter`.
http://localhost:5173/typesense-instantsearch-adapter@2.9.0

Warn CJS with default export and `__esModule` marker using `exports.["default"]`
